#!/usr/bin/env bash
# This script transfers a file

if [ $# -le 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

echo "scp -T -i $4 $1 $3@$2:~/"

scp -T -i $4 $1 $3@$2:~/
