#!/usr/bin/env bash
# Script to configure a load-balancing server

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy

echo \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend nodes

backend nodes
	mode http
	balance roundrobin
	server 1052-web-01 34.74.54.243
	server 1052-web-02 54.88.109.235" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
