#!/usr/bin/env bash
#Prints different strings depending on while loop iteration
x=1
while [ $x -le 20 ]
do
	if [ $x == 4 ]
	then
		echo "bad luck from China"
	elif [ $x == 9 ]
	then
		echo "bad luck from Japan"
	elif [ $x == 17 ]
	then
		echo "bad luck from Italy"
	else
		echo "$x"
	fi

	x=$(( x + 1 ))
done
